### ISSUE TITLE
Cant Load Assets When Use Published App

### ISSUE THREAD

**Issue by kitUIN** [dnchattan/winui-extensions#4]
I Use Image in SamplePage of the SampleExtension
It is load Asset Picture normally when I Debug
I Publish this sample app to Unpackaged App and It can't load Asset Picture when i use it
 
Actually it is normal when Debug, can't load when Run

**Comment by kitUIN** [comment]
```
08-07 20:55:09.588 [EROR]  | LoadComponent:Microsoft.UI.Xaml.Markup.XamlParseException: XAML parsing failed.
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|20_0(Int32 hr)
   at ABI.Microsoft.UI.Xaml.IApplicationStaticsMethods.LoadComponent(IObjectReference _obj, Object component, Uri resourceLocator, ComponentResourceLocation componentResourceLocation)
   at Microsoft.UI.Xaml.Application.LoadComponent(Object component, Uri resourceLocator, ComponentResourceLocation componentResourceLocation)
   at CustomExtensions.WinUI.WinUIExtensions.LoadComponent[T](T component, Boolean& contentLoaded, String callerFilePath) in C:\Users\15854\source\repos\winui-extensions\CustomExtensions.WinUI\WinUIExtensions.cs:line 23 

```

**Comment by kitUIN** [comment]
this way need WindowsApps Folder Permissions
